package org.jetbrains.space.jenkins

import com.fasterxml.jackson.databind.ObjectMapper
import jenkins.model.Jenkins
import java.io.File

public val reactAppIndexHtml by lazy {
    val webAppReactDir = File(Jenkins.get().getPluginManager().getPlugin("jetbrains-space")!!.baseResourceURL.file, "react")
    val jenkins = Jenkins.get()
    val jenkinsRootUrl = jenkins.rootUrl!!.trimEnd('/')
    File(webAppReactDir, "index.html").readText()
        .replace("/\$JENKINS_ROOT", jenkinsRootUrl)
        .replace("\$RES_ROOT", "$jenkinsRootUrl/static/${Jenkins.VERSION_HASH}")
}

/**
 * HTML content of the page that completes the SpaceCode OAuth flow and gets the OAuth code that can be exchanged for access token.
 */
public val oAuthCompleteHtml by lazy {
    val webAppJsDir = File(Jenkins.get().getPluginManager().getPlugin("jetbrains-space")!!.baseResourceURL.file, "js")
    File(webAppJsDir, "oauthComplete.html").readText()
}

/**
 * Reads the React application manifest generated by the webpack
 */
private val reactAppManifestJson by lazy {
    val webAppReactDir = File(Jenkins.get().getPluginManager().getPlugin("jetbrains-space")!!.baseResourceURL.file, "react")
    ObjectMapper().readTree(File(webAppReactDir, "asset-manifest.json"))
}

/**
 * Runtime URL of the React app javascript file
 */
public val reactAppJsPath by lazy {
    reactAppManifestJson["files"]["main.js"].asText().replace("/\$JENKINS_ROOT", Jenkins.get().rootUrl!!.trimEnd('/'))
}

/**
 * Runtime URL of the React app css file
 */
public val reactAppCssPath by lazy {
    reactAppManifestJson["files"]["main.css"].asText().replace("/\$JENKINS_ROOT", Jenkins.get().rootUrl!!.trimEnd('/'))
}